### ISSUE TITLE
我想训练一个java的领域分词模型

### ISSUE THREAD

**Issue by 172184221** [luozhouyang/deepseg#2]
网上找了找有没有相关训练自己的分词模型的，看到了您的项目。但是不知道能不能出个java方式的。

**Comment by luozhouyang** [comment]
一般情况下，训练神经网络都是使用python。但是训练好的模型，可以使用tensorflow serving部署，提供RPC和HTTP借口，可以直接调用。这样来看的话，没必要使用Java。
